persian translation files
apiato/apiato pull request #597
Opened 2020-12-12 13:38 UTC by wikiccu

about issue :  #595 
## Description
I just translated locale files for the Persian language

special thanks to all members for building this great project <3

2020-12-17 16:50 UTC, moslem-deris requested changes

2020-12-17 16:50 UTC, moslem-deris commented on resources/lang/fa/pagination.php
> +    'previous' => '&laquo; قبلی',
This is a translation file, please only enter translated phrases, words and sentences and avoid using HTML character codes

2020-12-17 16:50 UTC, moslem-deris commented on resources/lang/fa/validation.php
> +    'alpha_dash'           => ':attribute باید فقط حروف الفبا، اعداد، خط تیره و زیرخط باشد.',
In my opinion instead of `و زیرخط` its better to say `یا زیرخط`

2020-12-17 16:55 UTC, Mohammad-Alavi commented on resources/lang/fa/validation.php
> +    'alpha_dash'           => ':attribute باید فقط حروف الفبا، اعداد، خط تیره و زیرخط باشد.',
I agree with this change. Please implement it so we can merge this PR.

2021-03-07 13:45 UTC, moslem-deris commented
@wikiccu Check review comments and apply needed changes so we can merge your PR, thank you.

2021-03-25 12:46 UTC, Mohammad-Alavi commented on resources/lang/fa/validation.php
> +    'alpha_dash'           => ':attribute باید فقط حروف الفبا، اعداد، خط تیره و زیرخط باشد.',
Ill fix this small issue after merge.

2021-03-25 12:47 UTC, merged